import React, { Component } from "react";
import { connect } from "react-redux";
import Space from "./Space";
import SpaceDetailed from "components/SpaceDetailed";
import { range } from "utils";
import MiddleBoard from "./MiddleBoard";
import { togglePropertyModal } from "redux/actions";
import "./style.css";

class Board extends Component {
  //adhoc thing do not rely on this for a long term solution
  //ideally this should be generated by the server
  getPlayerName = (myId, id) => {
    if (myId === id) {
      return "human";
    }
    return "robot";
  };

  getPlayerOnPosition = index => {
    const { playersPositions, myId } = this.props;
    for (let playerId in playersPositions) {
      if (index === playersPositions[playerId]) {
        return { present: true, player: this.getPlayerName(playerId, myId) };
      }
    }
    return { present: false, player: "" };
  };

  getOwned = space => {
    const { players, myId } = this.props;
    if (space.owned && players.indexOf(space.ownerId) !== -1) {
      return { owned: true, owner: this.getPlayerName(space.ownerId, myId) };
    }
    return { owned: false, owner: "" };
  };

  getSpaceProps = index => {
    const { properties, candidates, togglePropertyModal } = this.props;
    const space = properties[index];
    const key = index;
    const highlighted = candidates.indexOf(index) !== -1 ? true : false;
    const owned = this.getOwned(index);
    const playerOnPosition = this.getPlayerOnPosition(index);

    return {
      index,
      space,
      key,
      highlighted,
      playerOnPosition,
      owned,
      togglePropertyModal
    };
  };

  render() {
    const { getSpaceProps } = this;

    return (
      <div className="monopoly-table">
        {/* Start of Board */}
        <div className="board">
          <MiddleBoard />

          {/* Actual Grids go here */}
          <Space {...getSpaceProps(0)} />

          {/* Bottom Section */}
          <div className="board-row horizontal-board-row bottom-board-row">
            {range(9).map(index => (
              <Space {...getSpaceProps(10 - (index + 1))} />
            ))}
          </div>

          <Space {...getSpaceProps(10)} />

          {/* Left Section */}
          <div className="board-row vertical-board-row left-board-row">
            {range(9).map(index => (
              <Space {...getSpaceProps(20 - (index + 1))} />
            ))}
          </div>

          <Space {...getSpaceProps(20)} />

          {/* Top Section */}
          <div className="board-row horizontal-board-row top-board-row">
            {range(9).map((prop, index) => (
              <Space {...getSpaceProps(21 + index)} />
            ))}
          </div>

          <Space {...getSpaceProps(30)} />

          {/* Right Section */}
          <div className="board-row vertical-board-row right-board-row">
            {range(9).map((prop, index) => (
              <Space {...getSpaceProps(31 + index)} />
            ))}
          </div>
          {/* End of Game Playing Grids */}
        </div>
        <SpaceDetailed />
      </div>
    );
  }
}

const mapDispatchToProps = dispatch => {
  return {
    togglePropertyModal: (showPropertyModal, selectedPropertyIndex) =>
      dispatch(togglePropertyModal(showPropertyModal, selectedPropertyIndex))
  };
};

const mapStateToProps = state => {
  return {
    myId: state.myId,
    players: state.players || [],
    properties: state.properties,
    candidates: state.candidates || [],
    playersPositions: state.playersPositions
  };
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Board);
