const data = {
    "0": {
        "class": "corner go",
        "hotel": false,
        "houses": 0,
        "id": 0,
        "instructions": "Collect $200.00 salary as you pass",
        "monopoly": "None",
        "mortgaged": false,
        "name": "Go",
        "owned": false,
        "ownerId": 0
    },
    "1": {
        "build_cost": 50,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 1,
        "monopoly": "brown",
        "monopoly_group_elements": [3],
        "monopoly_group_id": 0,
        "monopoly_size": 2,
        "mortgaged": false,
        "name": "Mediterranean Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 60,
        "rent": [2, 10, 30, 90, 160, 250],
        "tax": 0
    },
    "2": {
        "class": "chest",
        "hotel": false,
        "houses": 0,
        "id": 2,
        "instructions": "Follow instructions on top card",
        "mortgaged": false,
        "name": "Community Chest",
        "owned": false,
        "ownerId": 0
    },
    "3": {
        "build_cost": 50,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 3,
        "monopoly": "brown",
        "monopoly_group_elements": [1],
        "monopoly_group_id": 0,
        "monopoly_size": 2,
        "mortgaged": false,
        "name": "Baltic Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 60,
        "rent": [4, 20, 60, 180, 320, 450],
        "tax": 0
    },
    "4": {
        "class": "income-tax",
        "hotel": false,
        "houses": 0,
        "id": 4,
        "mortgaged": false,
        "name": "Income Tax",
        "owned": false,
        "ownerId": 0,
        "tax": 200
    },
    "5": {
        "build_cost": 0,
        "class": "railroad",
        "hotel": false,
        "houses": 0,
        "id": 5,
        "monopoly": "Railroad",
        "monopoly_group_elements": [15, 25, 35],
        "monopoly_group_id": 1,
        "monopoly_size": 4,
        "mortgaged": false,
        "name": "Reading Railroad",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 200,
        "rent": [25, 50, 100, 200, 0, 0],
        "tax": 0
    },
    "6": {
        "build_cost": 50,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 6,
        "monopoly": "light-blue",
        "monopoly_group_elements": [8, 9],
        "monopoly_group_id": 2,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Oriental Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 100,
        "rent": [6, 30, 90, 270, 400, 550],
        "tax": 0
    },
    "7": {
        "class": "chance",
        "hotel": false,
        "houses": 0,
        "id": 7,
        "instructions": "Follow instructions on top card",
        "mortgaged": false,
        "name": "Chance",
        "owned": false,
        "ownerId": 0
    },
    "8": {
        "build_cost": 50,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 8,
        "monopoly": "light-blue",
        "monopoly_group_elements": [6, 9],
        "monopoly_group_id": 2,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Vermont Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 100,
        "rent": [6, 30, 90, 270, 400, 550],
        "tax": 0
    },
    "9": {
        "build_cost": 50,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 9,
        "monopoly": "light-blue",
        "monopoly_group_elements": [6, 8],
        "monopoly_group_id": 2,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Connecticut Avenue",
        "owned": false,
        "ownerId": 0,
        "price": 120,
        "rent": [8, 40, 100, 300, 450, 600],
        "tax": 0
    },
    "10": {
        "class": "corner jail",
        "hotel": false,
        "houses": 0,
        "id": 10,
        "mortgaged": false,
        "name": "Jail",
        "owned": false,
        "ownerId": 0
    },
    "11": {
        "build_cost": 100,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 11,
        "monopoly": "pink",
        "monopoly_group_elements": [13, 14],
        "monopoly_group_id": 3,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "St. Charles Place",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 140,
        "rent": [10, 50, 150, 450, 625, 750],
        "tax": 0
    },
    "12": {
        "build_cost": 0,
        "class": "utility electric-company",
        "hotel": false,
        "houses": 0,
        "id": 12,
        "monopoly": "Utility",
        "monopoly_group_elements": [28],
        "monopoly_group_id": 4,
        "monopoly_size": 2,
        "mortgaged": false,
        "name": "Electric Company",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 150,
        "rent": [4, 10, 0, 0, 0, 0],
        "tax": 0
    },
    "13": {
        "build_cost": 100,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 13,
        "monopoly": "pink",
        "monopoly_group_elements": [11, 14],
        "monopoly_group_id": 3,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "States Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 140,
        "rent": [10, 50, 150, 450, 625, 750],
        "tax": 0
    },
    "14": {
        "build_cost": 100,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 14,
        "monopoly": "pink",
        "monopoly_group_elements": [11, 13],
        "monopoly_group_id": 3,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Virginia Avenue",
        "owned": false,
        "ownerId": 0,
        "price": 160,
        "rent": [12, 60, 180, 500, 700, 900],
        "tax": 0
    },
    "15": {
        "build_cost": 0,
        "class": "railroad",
        "hotel": false,
        "houses": 0,
        "id": 15,
        "monopoly": "railroad",
        "monopoly_group_elements": [5, 25, 35],
        "monopoly_group_id": 1,
        "monopoly_size": 4,
        "mortgaged": false,
        "name": "Pennsylvania Railroad",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 200,
        "rent": [25, 50, 100, 200, 0, 0],
        "tax": 0
    },
    "16": {
        "build_cost": 100,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 16,
        "monopoly": "orange",
        "monopoly_group_elements": [18, 19],
        "monopoly_group_id": 5,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "St. James Place",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 180,
        "rent": [14, 70, 200, 550, 750, 950],
        "tax": 0
    },
    "17": {
        "class": "chest",
        "hotel": false,
        "houses": 0,
        "id": 17,
        "instructions": "Follow instructions on top card",
        "mortgaged": false,
        "name": "Community Chest",
        "owned": false,
        "ownerId": 0
    },
    "18": {
        "build_cost": 100,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 18,
        "monopoly": "orange",
        "monopoly_group_elements": [16, 19],
        "monopoly_group_id": 5,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Tennessee Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 180,
        "rent": [14, 70, 200, 550, 750, 950],
        "tax": 0
    },
    "19": {
        "build_cost": 100,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 19,
        "monopoly": "orange",
        "monopoly_group_elements": [16, 18],
        "monopoly_group_id": 5,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "New York Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 200,
        "rent": [16, 80, 220, 600, 800, 1000],
        "tax": 0
    },
    "20": {
        "class": "corner free-parking",
        "hotel": false,
        "houses": 0,
        "id": 20,
        "mortgaged": false,
        "name": "Free Parking",
        "owned": false,
        "ownerId": 0
    },
    "21": {
        "build_cost": 150,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 21,
        "monopoly": "red",
        "monopoly_group_elements": [23, 24],
        "monopoly_group_id": 6,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Kentucky Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 220,
        "rent": [18, 90, 250, 700, 875, 1050],
        "tax": 0
    },
    "22": {
        "class": "chance",
        "hotel": false,
        "houses": 0,
        "id": 22,
        "instructions": "Follow instructions on top card",
        "mortgaged": false,
        "name": "Chance",
        "owned": false,
        "ownerId": 0
    },
    "23": {
        "build_cost": 150,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 23,
        "monopoly": "red",
        "monopoly_group_elements": [21, 24],
        "monopoly_group_id": 6,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Indiana Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 220,
        "rent": [18, 90, 250, 700, 875, 1050],
        "tax": 0
    },
    "24": {
        "build_cost": 150,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 24,
        "monopoly": "red",
        "monopoly_group_elements": [21, 23],
        "monopoly_group_id": 6,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Illinois Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 240,
        "rent": [20, 100, 300, 750, 925, 1100],
        "tax": 0
    },
    "25": {
        "build_cost": 0,
        "class": "Railroad",
        "hotel": false,
        "houses": 0,
        "id": 25,
        "monopoly": "Railroad",
        "monopoly_group_elements": [5, 15, 35],
        "monopoly_group_id": 1,
        "monopoly_size": 4,
        "mortgaged": false,
        "name": "B. & O. Railroad",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 200,
        "rent": [25, 50, 100, 200, 0, 0],
        "tax": 0
    },
    "26": {
        "build_cost": 150,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 26,
        "monopoly": "yellow",
        "monopoly_group_elements": [27, 29],
        "monopoly_group_id": 7,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Atlantic Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 260,
        "rent": [22, 110, 330, 800, 975, 1150],
        "tax": 0
    },
    "27": {
        "build_cost": 150,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 27,
        "monopoly": "yellow",
        "monopoly_group_elements": [26, 29],
        "monopoly_group_id": 7,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Ventnor Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 260,
        "rent": [22, 110, 330, 800, 975, 1150],
        "tax": 0
    },
    "28": {
        "build_cost": 0,
        "class": "utility waterworks",
        "hotel": false,
        "houses": 0,
        "id": 28,
        "monopoly": "Utility",
        "monopoly_group_elements": [12],
        "monopoly_group_id": 4,
        "monopoly_size": 2,
        "mortgaged": false,
        "name": "Water Works",
        "owned": false,
        "ownerId": 0,
        "price": 150,
        "rent": [4, 10, 0, 0, 0, 0],
        "tax": 0
    },
    "29": {
        "build_cost": 150,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 29,
        "monopoly": "yellow",
        "monopoly_group_elements": [26, 27],
        "monopoly_group_id": 7,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Marvin Gardens",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 280,
        "rent": [24, 120, 360, 850, 1025, 1200],
        "tax": 0
    },
    "30": {
        "class": "go-to-jail",
        "hotel": false,
        "houses": 0,
        "id": 30,
        "mortgaged": false,
        "name": "Go To Jail",
        "owned": false,
        "ownerId": 0
    },
    "31": {
        "build_cost": 200,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 31,
        "monopoly": "green",
        "monopoly_group_elements": [32, 34],
        "monopoly_group_id": 8,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Pacific Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 300,
        "rent": [26, 130, 390, 900, 1100, 1275],
        "tax": 0
    },
    "32": {
        "build_cost": 200,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 32,
        "monopoly": "green",
        "monopoly_group_elements": [31, 34],
        "monopoly_group_id": 8,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "North Carolina Avenue",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 300,
        "rent": [26, 130, 390, 900, 1100, 1275],
        "tax": 0
    },
    "33": {
        "class": "chest",
        "hotel": false,
        "houses": 0,
        "id": 33,
        "mortgaged": false,
        "name": "Community Chest",
        "owned": false,
        "ownerId": 0
    },
    "34": {
        "build_cost": 200,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 34,
        "monopoly": "green",
        "monopoly_group_elements": [31, 32],
        "monopoly_group_id": 8,
        "monopoly_size": 3,
        "mortgaged": false,
        "name": "Pennsylvania Avenue",
        "owned": true,
        "ownerId": "iwWxalZSKSMKvSPZBtxFl7Bbko1OTeBAT7IReUmU0engIoJqmU",
        "price": 320,
        "rent": [28, 150, 450, 1000, 1200, 1400],
        "tax": 0
    },
    "35": {
        "build_cost": 0,
        "class": "railroad",
        "hotel": false,
        "houses": 0,
        "id": 35,
        "monopoly": "Railroad",
        "monopoly_group_elements": [5, 15, 25],
        "monopoly_group_id": 1,
        "monopoly_size": 4,
        "mortgaged": false,
        "name": "Short Line",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 200,
        "rent": [25, 50, 100, 200, 0, 0],
        "tax": 0
    },
    "36": {
        "build_cost": 0,
        "class": "chance",
        "hotel": false,
        "houses": 0,
        "id": 36,
        "monopoly": "None",
        "monopoly_size": 0,
        "mortgaged": false,
        "name": "Chance",
        "owned": false,
        "price": 0,
        "rent": [0, 0, 0, 0, 0, 0],
        "tax": 0
    },
    "37": {
        "build_cost": 200,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 37,
        "monopoly": "dark-blue",
        "monopoly_group_elements": [39],
        "monopoly_group_id": 9,
        "monopoly_size": 2,
        "mortgaged": false,
        "name": "Park Place",
        "owned": false,
        "ownerId": 0,
        "price": 350,
        "rent": [35, 175, 500, 1100, 1300, 1500],
        "tax": 0
    },
    "38": {
        "class": "luxury-tax",
        "hotel": false,
        "houses": 0,
        "id": 38,
        "mortgaged": false,
        "name": "Luxury Tax",
        "owned": false,
        "ownerId": 0,
        "tax": 100
    },
    "39": {
        "build_cost": 200,
        "class": "street",
        "hotel": false,
        "houses": 0,
        "id": 39,
        "monopoly": "dark-blue",
        "monopoly_group_elements": [37],
        "monopoly_group_id": 9,
        "monopoly_size": 2,
        "mortgaged": false,
        "name": "Boardwalk",
        "owned": true,
        "ownerId": "GPFiRA8WCTn478F5Lr7C1wciGqLqE8M73YylYUAonaaJKmZjjU",
        "price": 400,
        "rent": [50, 200, 600, 1400, 1700, 2000],
        "tax": 0
    }
};
module.exports = data;